export const dummyInventory = [
  {
    id: 1,
    kategori: "Stent",
    namaBarang: "Supraflex 3.0 x 32",
    lot: "(10)P25TZAELAB",
    ukuran: "3.0 x 32",
    stok: 12,
    ed: "2027-04-15",
    status: "NEW",
    vendor: "Sahabat Medika",
  },
  {
    id: 2,
    kategori: "Balloon",
    namaBarang: "Pantera LEO 2.5 x 20",
    lot: "(10)PL2X20-05",
    ukuran: "2.5 x 20",
    stok: 5,
    ed: "2025-11-10",
    status: "NEW",
    vendor: "Global Meditech",
  },
  {
    id: 3,
    kategori: "Microcatheter",
    namaBarang: "Finecross MG",
    lot: "(10)FMG2024",
    ukuran: "150 cm",
    stok: 2,
    ed: "2025-10-28",
    status: "REUSE",
    vendor: "Boston Scientific",
  },
];
